Update docs on policyset validation to use the official cedar validation
common-fate/docs-archive-2 pull request #21
Opened 2024-07-18 06:25 UTC by ckluy31

2024-07-19 13:38 UTC, chrnorm requested changes

2024-07-19 13:38 UTC, chrnorm commented on authz/ci.mdx
> +    cargo build --release
you can use `cargo install cedar-policy-cli` instead here

2024-07-19 13:38 UTC, chrnorm commented on authz/ci.mdx
> -KEY_FPATH=common-fate-signing-key.asc
the users will still need the `cf` CLI, so that they can run 
```bash
cf authz schema get > common-fate.cedarschema.json
```

otherwise they will have no way to download the Cedar schema to validate policies against

2024-07-19 13:38 UTC, chrnorm commented on authz/ci.mdx
> +find . -type f -name '*.cedar' | xargs -n1 cedar validate --schema common-fate.cedarschema.json --schema-format json --policies
I'm unsure if this will work on linux (I built and tested the command on MacOS, I think `find` and `xargs` _may_ be different)

You can just include an example of validating a single policy first:
```
cedar validate --schema entities/common-fate.cedarschema.json --policies default_policy_for_testing.cedar
```

and then include this as a follow-up example underneath, as an example of validating all `*.cedar` policies

2024-07-19 13:38 UTC, chrnorm commented on authz/validation.mdx
> -You'll also need the [Common Fate `cf` CLI installed](/user-guide/cli/quickstart) - v1.12.0 or higher. You can check this by running `cf --version`. You should see an output similar to the below
You still need the CF CLI as mentioned above

2024-07-19 13:38 UTC, chrnorm commented on authz/validation.mdx
> +1. Clone the [Cedar repository](https://github.com/cedar-policy/cedar) locally.
Same here, you can just run `cargo install` to get it

2024-07-22 23:36 UTC, ckluy31 commented on authz/ci.mdx
> +    cargo build --release
updated

2024-07-22 23:36 UTC, ckluy31 commented on authz/ci.mdx
> -KEY_FPATH=common-fate-signing-key.asc
added back

2024-07-22 23:36 UTC, ckluy31 commented on authz/ci.mdx
> +find . -type f -name '*.cedar' | xargs -n1 cedar validate --schema common-fate.cedarschema.json --schema-format json --policies
done

2024-07-22 23:37 UTC, ckluy31 commented on authz/validation.mdx
> +1. Clone the [Cedar repository](https://github.com/cedar-policy/cedar) locally.
updated

2024-07-22 23:37 UTC, ckluy31 commented on authz/validation.mdx
> -You'll also need the [Common Fate `cf` CLI installed](/user-guide/cli/quickstart) - v1.12.0 or higher. You can check this by running `cf --version`. You should see an output similar to the below
added back

2024-07-24 03:23 UTC, JoshuaWilkes approved these changes

2024-07-24 03:23 UTC, merged